// <auto-generated />
using raptorSlot.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace raptorSlot.Migrations
{
    [DbContext(typeof(OsobaContext))]
    partial class OsobaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("raptorSlot.Models.Osoba", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("imie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nazwisko")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("waga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wzrostCM")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Osoby");
                });
#pragma warning restore 612, 618
        }
    }
}
